INSERT INTO categories (id, parentId, name) VALUES (1, NULL, 'Tilat');
INSERT INTO categories (id, parentId, name) VALUES (2, 1, 'Asuintilat');
INSERT INTO categories (id, parentId, name) VALUES (3, 2, 'Asuinhuone');
INSERT INTO categories (id, parentId, name) VALUES (4, 2, 'Eteinen');
INSERT INTO categories (id, parentId, name) VALUES (5, 2, 'Ikkunat');
INSERT INTO categories (id, parentId, name) VALUES (6, 2, 'Keittiö ');
INSERT INTO categories (id, parentId, name) VALUES (7, 2, 'Liikkumisen tilantarve, mitoitus');
INSERT INTO categories (id, parentId, name) VALUES (8, 2, 'Luiska');
INSERT INTO categories (id, parentId, name) VALUES (9, 2, 'Makuuhuone');
INSERT INTO categories (id, parentId, name) VALUES (10, 2, 'Ovet');
INSERT INTO categories (id, parentId, name) VALUES (11, 10, 'Sisäovet');
INSERT INTO categories (id, parentId, name) VALUES (12, 10, 'Ulko-ovet');
INSERT INTO categories (id, parentId, name) VALUES (13, 2, 'Parveke/terassi');
INSERT INTO categories (id, parentId, name) VALUES (14, 2, 'Pesuhuone');
INSERT INTO categories (id, parentId, name) VALUES (15, 2, 'Portaat');
INSERT INTO categories (id, parentId, name) VALUES (16, 2, 'Pukuhuone');
INSERT INTO categories (id, parentId, name) VALUES (17, 2, 'Ruokailutila');
INSERT INTO categories (id, parentId, name) VALUES (18, 2, 'Sauna');
INSERT INTO categories (id, parentId, name) VALUES (19, 2, 'Sisäänkäynti ja tuulikaappi ');
INSERT INTO categories (id, parentId, name) VALUES (20, 2, 'WC-/peseytymistila');
INSERT INTO categories (id, parentId, name) VALUES (21, 2, 'WC');
INSERT INTO categories (id, parentId, name) VALUES (22, 1, 'Rakennuksen yhteistilat');
INSERT INTO categories (id, parentId, name) VALUES (23, 22, 'Aula- ja käytävätilat ');
INSERT INTO categories (id, parentId, name) VALUES (24, 22, 'Hissi');
INSERT INTO categories (id, parentId, name) VALUES (25, 22, 'Jätetila');
INSERT INTO categories (id, parentId, name) VALUES (26, 22, 'Keittiö ');
INSERT INTO categories (id, parentId, name) VALUES (27, 22, 'Kerhotila');
INSERT INTO categories (id, parentId, name) VALUES (28, 22, 'Liikkumisen tilantarve, mitoitus ');
INSERT INTO categories (id, parentId, name) VALUES (29, 22, 'Liikkumisvälinevarasto');
INSERT INTO categories (id, parentId, name) VALUES (30, 22, 'Luiska');
INSERT INTO categories (id, parentId, name) VALUES (31, 22, 'Opastus');
INSERT INTO categories (id, parentId, name) VALUES (32, 22, 'Ovet');
INSERT INTO categories (id, parentId, name) VALUES (33, 32, 'Sisäovet');
INSERT INTO categories (id, parentId, name) VALUES (34, 32, 'Ulko-ovet');
INSERT INTO categories (id, parentId, name) VALUES (35, 22, 'Parveke/terassi');
INSERT INTO categories (id, parentId, name) VALUES (36, 22, 'Pesuhuone');
INSERT INTO categories (id, parentId, name) VALUES (37, 22, 'Pesula');
INSERT INTO categories (id, parentId, name) VALUES (38, 22, 'Porrashuone');
INSERT INTO categories (id, parentId, name) VALUES (39, 22, 'Portaat');
INSERT INTO categories (id, parentId, name) VALUES (40, 22, 'Pukuhuone');
INSERT INTO categories (id, parentId, name) VALUES (41, 22, 'Sauna');
INSERT INTO categories (id, parentId, name) VALUES (42, 22, 'Sisäänkäynti ja tuulikaappi ');
INSERT INTO categories (id, parentId, name) VALUES (43, 22, 'WC, pyörätuolimitoitus');
INSERT INTO categories (id, parentId, name) VALUES (44, 22, 'WC');
INSERT INTO categories (id, parentId, name) VALUES (45, 1, 'Ulkotilat');
INSERT INTO categories (id, parentId, name) VALUES (46, 45, 'Autopaikat');
INSERT INTO categories (id, parentId, name) VALUES (47, 45, 'Jätetila');
INSERT INTO categories (id, parentId, name) VALUES (48, 45, 'Kulkuväylä ulkona');
INSERT INTO categories (id, parentId, name) VALUES (49, 45, 'Liikkumisvälinevarasto');
INSERT INTO categories (id, parentId, name) VALUES (50, 45, 'Luiska');
INSERT INTO categories (id, parentId, name) VALUES (51, 45, 'Opastus');
INSERT INTO categories (id, parentId, name) VALUES (52, 45, 'Ulkoportaat ');
INSERT INTO categories (id, parentId, name) VALUES (53, 45, 'Yhteistilat ulkona');